### ISSUE TITLE
Site v1 (Mockups)

### ISSUE THREAD

**Issue by zachberry** [ucfopen/ucfopen.github.io#1]
Mockup for the first iteration of the site. SVGs are available for the logos and the library graphic 

![ucf-open-landingpage-quickidea-4](https://user-images.githubusercontent.com/73479/63049165-16ed2680-bea6-11e9-94dc-3dbafd505c88.png)

**Comment by bagofarms** [comment]
I like the mockup.  It did raise a question, though.  When we write UCF Open outside of a logo, is it: `UCF Open`, `ucfopen`, `UCFOpen` or some other variation?

**Comment by iturgeon** [comment]
Closing as the mockup is real now
